spring:
  application:
    name: spring-ai

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      chat:
        base-url: https://api.groq.com/openai
        options:
          model: llama-3.2-90b-vision-preview
